{% set version = "1.1" %}

package:
  name: apu-label-propagation
  version: {{ version }}

source:
  url: https://github.com/anuprulez/apu_label_propagation/archive/refs/tags/1.1.tar.gz
  sha256: 0e263916c44d733fb0d45bcff92f5a91fff6825de068e64b9d70208ed1375739

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('apu-label-propagation') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

test:
  commands:
    - apu-label-propagation

about:
  home: https://github.com/AndMastro/NIAPU
  license: MIT
  summary: Adaptive Positive-Unlabelled label propagation
