{% set version = "1.1" %}

package:
  name: apu-label-propagation
  version: {{ version }}

source:
  url: https://github.com/anuprulez/apu_label_propagation/archive/refs/tags/1.0.tar.gz
  sha256: 71d4fb4f37f50a366a629f61b2866f54a5ea06301462d142c65f8170f1dfa96a

build:
  number: 0
  skip: True
  run_exports:
    - {{ pin_subpackage('apu-label-propagation') }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - python >= 3.9
    - gcc >= 11.4.0

test:
  imports:
    - apu-label-propagation

about:
  home: https://github.com/AndMastro/NIAPU
  license: MIT LICENSE
  summary: Adaptive Positive-Unlabelled label propagation
