package:
  name: apu-label-propagation
  version: "1.0"

source:
  url: https://github.com/anuprulez/apu_label_propagation/archive/refs/tags/1.0.tar.gz
  sha256: 71d4fb4f37f50a366a629f61b2866f54a5ea06301462d142c65f8170f1dfa96a

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  run:
    - gcc >=11.4.0

test:
  commands:
    - apu-label-propagation --version

about:
  home: https://github.com/AndMastro/NIAPU
  license: MIT LICENSE
  summary: Adaptive Positive-Unlabelled label propagation
